"""club directory link

Revision ID: b17b99727013
Revises: 6d962b1c1340
Created: 2026-08-14 20:25:02.549880+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b17b99727013"
down_revision: str | None = "6d962b1c1340"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("club", sa.Column("directory_club_id", sa.UUID(), nullable=True))
    op.drop_column("tenant", "directory_club_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant", sa.Column("directory_club_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_column("club", "directory_club_id")
    # ### end Alembic commands ###
