"""competitions and matches

Revision ID: 6d962b1c1340
Revises: e71b3d5a9042
Created: 2026-08-14 20:11:15.221469+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d962b1c1340"
down_revision: str | None = "e71b3d5a9042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("endonym", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(code) = 2", name=op.f("ck_country_country_code_is_alpha2")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country")),
        sa.UniqueConstraint("code", name="uq_country_code"),
    )
    op.create_table(
        "competition",
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=32), nullable=True),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=True),
        sa.Column("badge_media_id", sa.UUID(), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'DOMESTIC_LEAGUE') = (tier IS NOT NULL)",
            name=op.f("ck_competition_competition_tier_matches_scope"),
        ),
        sa.CheckConstraint(
            "format IN ('LEAGUE', 'KNOCKOUT', 'GROUP_KNOCKOUT')",
            name=op.f("ck_competition_competition_format_valid"),
        ),
        sa.CheckConstraint(
            "scope IN ('DOMESTIC_LEAGUE', 'DOMESTIC_CUP', 'CONTINENTAL', 'FRIENDLY')",
            name=op.f("ck_competition_competition_scope_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
            name=op.f("fk_competition_country_id_country"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition")),
        sa.UniqueConstraint("country_id", "key", name="uq_competition_key"),
    )
    op.create_index(
        "ix_competition_country", "competition", ["country_id", "tier"], unique=False
    )
    op.create_table(
        "directory_club",
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=16), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("crest_url", sa.String(length=500), nullable=True),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
            name=op.f("fk_directory_club_country_id_country"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directory_club")),
        sa.UniqueConstraint("slug", name="uq_directory_club_slug"),
    )
    op.create_index(
        "ix_directory_club_country", "directory_club", ["country_id", "name"], unique=False
    )
    op.create_table(
        "competition_season",
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("points_for_win", sa.SmallInteger(), nullable=False),
        sa.Column("points_for_draw", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date > start_date",
            name=op.f("ck_competition_season_competition_season_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competition.id"],
            name=op.f("fk_competition_season_competition_id_competition"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_season")),
        sa.UniqueConstraint("competition_id", "name", name="uq_competition_season_name"),
    )
    op.create_index(
        "ix_competition_season_current",
        "competition_season",
        ["competition_id", "is_current"],
        unique=False,
    )
    op.create_table(
        "competition_entry",
        sa.Column("competition_season_id", sa.UUID(), nullable=False),
        sa.Column("directory_club_id", sa.UUID(), nullable=False),
        sa.Column("group_label", sa.String(length=8), nullable=True),
        sa.Column("points_adjustment", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_season_id"],
            ["competition_season.id"],
            name=op.f("fk_competition_entry_competition_season_id_competition_season"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["directory_club_id"],
            ["directory_club.id"],
            name=op.f("fk_competition_entry_directory_club_id_directory_club"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_entry")),
        sa.UniqueConstraint(
            "competition_season_id", "directory_club_id", name="uq_competition_entry"
        ),
    )
    op.create_index(
        "ix_competition_entry_club", "competition_entry", ["directory_club_id"], unique=False
    )
    op.create_table(
        "match",
        sa.Column("competition_season_id", sa.UUID(), nullable=False),
        sa.Column("home_club_id", sa.UUID(), nullable=False),
        sa.Column("away_club_id", sa.UUID(), nullable=False),
        sa.Column("round_kind", sa.String(length=12), nullable=False),
        sa.Column("round_number", sa.SmallInteger(), nullable=True),
        sa.Column("round_label", sa.String(length=48), nullable=True),
        sa.Column("group_label", sa.String(length=8), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kickoff_is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("venue_name", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.Column("attendance", sa.SmallInteger(), nullable=True),
        sa.Column("ticket_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('FINISHED', 'AWARDED')) = (home_score IS NOT NULL AND away_score IS NOT NULL)",
            name=op.f("ck_match_match_score_matches_status"),
        ),
        sa.CheckConstraint(
            "round_kind IN ('MATCHDAY', 'STAGE', 'GROUP')",
            name=op.f("ck_match_match_round_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('SCHEDULED', 'LIVE', 'FINISHED', 'POSTPONED', 'CANCELLED', 'AWARDED')",
            name=op.f("ck_match_match_status_valid"),
        ),
        sa.CheckConstraint(
            "away_score IS NULL OR away_score >= 0",
            name=op.f("ck_match_match_away_score_non_negative"),
        ),
        sa.CheckConstraint(
            "home_club_id <> away_club_id", name=op.f("ck_match_match_teams_differ")
        ),
        sa.CheckConstraint(
            "home_score IS NULL OR home_score >= 0",
            name=op.f("ck_match_match_home_score_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["away_club_id"],
            ["directory_club.id"],
            name=op.f("fk_match_away_club_id_directory_club"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["competition_season_id"],
            ["competition_season.id"],
            name=op.f("fk_match_competition_season_id_competition_season"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["home_club_id"],
            ["directory_club.id"],
            name=op.f("fk_match_home_club_id_directory_club"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
    )
    op.create_index("ix_match_away", "match", ["away_club_id", "kickoff_at"], unique=False)
    op.create_index("ix_match_home", "match", ["home_club_id", "kickoff_at"], unique=False)
    op.create_index(
        "ix_match_season_kickoff",
        "match",
        ["competition_season_id", "kickoff_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_season_kickoff", table_name="match")
    op.drop_index("ix_match_home", table_name="match")
    op.drop_index("ix_match_away", table_name="match")
    op.drop_table("match")
    op.drop_index("ix_competition_entry_club", table_name="competition_entry")
    op.drop_table("competition_entry")
    op.drop_index("ix_competition_season_current", table_name="competition_season")
    op.drop_table("competition_season")
    op.drop_index("ix_directory_club_country", table_name="directory_club")
    op.drop_table("directory_club")
    op.drop_index("ix_competition_country", table_name="competition")
    op.drop_table("competition")
    op.drop_table("country")
    # ### end Alembic commands ###
