"""cms content

Revision ID: 37a0dc6e78e0
Revises: 3043c5982317
Created: 2026-08-14 09:07:57.718574+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all
from sqlalchemy.dialects import postgresql

revision: str = "37a0dc6e78e0"
down_revision: str | None = "3043c5982317"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RLS_TABLES = ["content_category", "content_item", "content_translation"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_category",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "club_id"],
            ["club.tenant_id", "club.id"],
            name="fk_content_category_club",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_content_category_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_category")),
        sa.UniqueConstraint("tenant_id", "club_id", "key", name="uq_content_category_key"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_content_category_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_content_category_tenant_id"), "content_category", ["tenant_id"], unique=False
    )
    op.create_table(
        "content_item",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("author_person_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(status <> 'PUBLISHED') OR (published_at IS NOT NULL)",
            name=op.f("ck_content_item_content_item_published_needs_date"),
        ),
        sa.CheckConstraint(
            "(status <> 'SCHEDULED') OR (scheduled_for IS NOT NULL)",
            name=op.f("ck_content_item_content_item_scheduled_needs_date"),
        ),
        sa.CheckConstraint(
            "kind IN ('ARTICLE', 'PAGE')", name=op.f("ck_content_item_content_item_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'IN_REVIEW', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED')",
            name=op.f("ck_content_item_content_item_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["content_category.tenant_id", "content_category.id"],
            name="fk_content_item_category",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "club_id"],
            ["club.tenant_id", "club.id"],
            name="fk_content_item_club",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_content_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_item")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_content_item_tenant_id_id"),
    )
    op.create_index(
        "ix_content_due",
        "content_item",
        ["scheduled_for"],
        unique=False,
        postgresql_where="status = 'SCHEDULED'",
    )
    op.create_index(
        op.f("ix_content_item_tenant_id"), "content_item", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_content_published",
        "content_item",
        ["tenant_id", "club_id", "published_at"],
        unique=False,
        postgresql_where="status = 'PUBLISHED'",
    )
    op.create_index(
        "ix_content_status", "content_item", ["tenant_id", "club_id", "status"], unique=False
    )
    op.create_table(
        "content_translation",
        sa.Column("content_item_id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=240), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo_title", sa.String(length=240), nullable=True),
        sa.Column("seo_description", sa.String(length=400), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("translated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'READY')",
            name=op.f("ck_content_translation_content_translation_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "content_item_id"],
            ["content_item.tenant_id", "content_item.id"],
            name="fk_content_translation_item",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_content_translation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_translation")),
        sa.UniqueConstraint("club_id", "locale", "slug", name="uq_content_translation_slug"),
        sa.UniqueConstraint(
            "content_item_id", "locale", name="uq_content_translation_item_locale"
        ),
    )
    op.create_index(
        "ix_content_translation_lookup",
        "content_translation",
        ["tenant_id", "club_id", "locale"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_translation_tenant_id"),
        "content_translation",
        ["tenant_id"],
        unique=False,
    )
    for statement in enable_all(RLS_TABLES):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)
    op.drop_index(op.f("ix_content_translation_tenant_id"), table_name="content_translation")
    op.drop_index("ix_content_translation_lookup", table_name="content_translation")
    op.drop_table("content_translation")
    op.drop_index("ix_content_status", table_name="content_item")
    op.drop_index(
        "ix_content_published",
        table_name="content_item",
        postgresql_where="status = 'PUBLISHED'",
    )
    op.drop_index(op.f("ix_content_item_tenant_id"), table_name="content_item")
    op.drop_index(
        "ix_content_due", table_name="content_item", postgresql_where="status = 'SCHEDULED'"
    )
    op.drop_table("content_item")
    op.drop_index(op.f("ix_content_category_tenant_id"), table_name="content_category")
    op.drop_table("content_category")
    # ### end Alembic commands ###
