"""per club league feed

Revision ID: ed70627d8dc8
Revises: 83f7a572116c
Created: 2026-08-15 09:17:08.812252+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["club_feed"]


revision: str = "ed70627d8dc8"
down_revision: str | None = "83f7a572116c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_feed",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("provider_team_id", sa.String(length=32), nullable=True),
        sa.Column("provider_team_name", sa.String(length=160), nullable=True),
        sa.Column("season_year", sa.SmallInteger(), nullable=True),
        sa.Column("sync_fixtures", sa.Boolean(), nullable=False),
        sa.Column("sync_standings", sa.Boolean(), nullable=False),
        sa.Column("sync_live", sa.Boolean(), nullable=False),
        sa.Column("live_interval_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("fixtures_interval_hours", sa.SmallInteger(), nullable=False),
        sa.Column("last_fixtures_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_standings_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_live_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('MANUAL', 'FEED')", name=op.f("ck_club_feed_club_feed_mode_valid")
        ),
        sa.CheckConstraint(
            "live_interval_minutes BETWEEN 1 AND 1440",
            name=op.f("ck_club_feed_club_feed_live_interval_sane"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_club_feed_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_feed")),
        sa.UniqueConstraint("tenant_id", "club_id", "provider", name="uq_club_feed_club"),
    )
    op.create_index("ix_club_feed_due", "club_feed", ["provider", "mode"], unique=False)
    op.create_index(op.f("ix_club_feed_tenant_id"), "club_feed", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    op.drop_index(op.f("ix_club_feed_tenant_id"), table_name="club_feed")
    op.drop_index("ix_club_feed_due", table_name="club_feed")
    op.drop_table("club_feed")
    # ### end Alembic commands ###
