"""analytics events

Revision ID: 8a1eadb86839
Revises: ca6a3f93b424
Created: 2026-08-15 15:27:40.725673+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["analytics_event"]
from sqlalchemy.dialects import postgresql

revision: str = "8a1eadb86839"
down_revision: str | None = "ca6a3f93b424"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_event",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("visitor_hash", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("referrer_host", sa.String(length=160), nullable=True),
        sa.Column("utm_source", sa.String(length=80), nullable=True),
        sa.Column("utm_medium", sa.String(length=80), nullable=True),
        sa.Column("utm_campaign", sa.String(length=120), nullable=True),
        sa.Column("device", sa.String(length=10), nullable=False),
        sa.Column("browser", sa.String(length=24), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("value_minor", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "device IN ('mobile', 'desktop', 'tablet', 'other')",
            name=op.f("ck_analytics_event_analytics_device_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('PAGEVIEW', 'SHOP_VIEW', 'BASKET_ADD', 'CHECKOUT', 'ORDER', 'NEWSLETTER_SIGNUP', 'ACCOUNT_SIGNUP', 'TICKET_CLICK')",
            name=op.f("ck_analytics_event_analytics_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_analytics_event_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_event")),
    )
    op.create_index(
        "ix_analytics_club_kind_time",
        "analytics_event",
        ["tenant_id", "club_id", "kind", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_analytics_club_time",
        "analytics_event",
        ["tenant_id", "club_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_event_tenant_id"), "analytics_event", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_analytics_session", "analytics_event", ["tenant_id", "session_id"], unique=False
    )
    op.alter_column(
        "email_template",
        "blocks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_template",
        "blocks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        existing_nullable=False,
    )
    op.drop_index("ix_analytics_session", table_name="analytics_event")
    op.drop_index(op.f("ix_analytics_event_tenant_id"), table_name="analytics_event")
    op.drop_index("ix_analytics_club_time", table_name="analytics_event")
    op.drop_index("ix_analytics_club_kind_time", table_name="analytics_event")
    op.drop_table("analytics_event")
    # ### end Alembic commands ###
