"""standings form

Revision ID: 65b5920b3068
Revises: c1f01629f9b8
Created: 2026-08-15 10:16:01.330937+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65b5920b3068"
down_revision: str | None = "c1f01629f9b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("club_season_record", sa.Column("form", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("club_season_record", "form")
    # ### end Alembic commands ###
