"""article cover image

Revision ID: b8164a3fa861
Revises: 5e229cbe4f42
Created: 2026-08-14 21:11:48.017235+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b8164a3fa861"
down_revision: str | None = "5e229cbe4f42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_item", sa.Column("cover_media_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_item", "cover_media_id")
    # ### end Alembic commands ###
