"""email marketing tables

Revision ID: ca6a3f93b424
Revises: addc1019f600
Created: 2026-08-15 15:23:24.728838+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["email_template", "campaign", "campaign_recipient"]
from sqlalchemy.dialects import postgresql

revision: str = "ca6a3f93b424"
down_revision: str | None = "addc1019f600"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_template",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("preheader", sa.String(length=200), nullable=True),
        sa.Column(
            "blocks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("cta_label", sa.String(length=48), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_email_template_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_template")),
        sa.UniqueConstraint("tenant_id", "club_id", "key", name="uq_email_template_key"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_email_template_tenant_id_id"),
    )
    op.create_index(
        "ix_email_template_club", "email_template", ["tenant_id", "club_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_template_tenant_id"), "email_template", ["tenant_id"], unique=False
    )
    op.create_table(
        "campaign",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("opened", sa.Integer(), nullable=False),
        sa.Column("clicked", sa.Integer(), nullable=False),
        sa.Column("unsubscribed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "audience IN ('NEWSLETTER', 'SUPPORTERS', 'EVERYONE')",
            name=op.f("ck_campaign_campaign_audience_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('NEWS', 'OFFER', 'MATCHDAY', 'MEMBERSHIP', 'ANNOUNCEMENT')",
            name=op.f("ck_campaign_campaign_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED', 'CANCELLED')",
            name=op.f("ck_campaign_campaign_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_id"],
            ["email_template.tenant_id", "email_template.id"],
            name="fk_campaign_template",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_campaign_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_campaign_tenant_id_id"),
    )
    op.create_index(
        "ix_campaign_club_status", "campaign", ["tenant_id", "club_id", "status"], unique=False
    )
    op.create_index(op.f("ix_campaign_tenant_id"), "campaign", ["tenant_id"], unique=False)
    op.create_table(
        "campaign_recipient",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SENT', 'FAILED', 'BOUNCED', 'UNSUBSCRIBED')",
            name=op.f("ck_campaign_recipient_recipient_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaign.tenant_id", "campaign.id"],
            name="fk_recipient_campaign",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_campaign_recipient_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_recipient")),
        sa.UniqueConstraint("campaign_id", "email", name="uq_recipient_once"),
    )
    op.create_index(
        op.f("ix_campaign_recipient_tenant_id"),
        "campaign_recipient",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_recipient_campaign_status",
        "campaign_recipient",
        ["tenant_id", "campaign_id", "status"],
        unique=False,
    )
    op.alter_column(
        "club_branding",
        "sponsors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "club_branding",
        "sponsors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        existing_nullable=False,
    )
    op.drop_index("ix_recipient_campaign_status", table_name="campaign_recipient")
    op.drop_index(op.f("ix_campaign_recipient_tenant_id"), table_name="campaign_recipient")
    op.drop_table("campaign_recipient")
    op.drop_index(op.f("ix_campaign_tenant_id"), table_name="campaign")
    op.drop_index("ix_campaign_club_status", table_name="campaign")
    op.drop_table("campaign")
    op.drop_index(op.f("ix_email_template_tenant_id"), table_name="email_template")
    op.drop_index("ix_email_template_club", table_name="email_template")
    op.drop_table("email_template")
    # ### end Alembic commands ###
