"""events audit billing

Revision ID: 336b1da574fb
Revises: 8d4e0b17c992
Created: 2026-08-13 21:04:37.804412+00:00
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.audit.maintenance import partition_statements
from app.core.rls import disable_all, enable_all

revision: str = "336b1da574fb"
down_revision: str | None = "8d4e0b17c992"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# New tenant-scoped tables. `outbox_event` and `processed_event` are
# deliberately excluded: the relay claims rows across all tenants before any
# tenant context exists, and both are reachable only by platform-role
# processes. Plan and feature tables are global reference data.
RLS_TABLES = ["audit_log", "entitlement", "tenant_subscription"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("club_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("impersonated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('USER', 'SYSTEM', 'PLATFORM', 'SCANNER', 'API_KEY')",
            name=op.f("ck_audit_log_audit_actor_kind_valid"),
        ),
        sa.PrimaryKeyConstraint("id", "occurred_at", name=op.f("pk_audit_log")),
        postgresql_partition_by="RANGE (occurred_at)",
    )
    op.create_index(
        "ix_audit_actor", "audit_log", ["actor_user_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_object",
        "audit_log",
        ["tenant_id", "object_type", "object_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_tenant_time", "audit_log", ["tenant_id", "occurred_at"], unique=False
    )
    op.create_table(
        "feature",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_enabled", sa.Boolean(), nullable=False),
        sa.Column("default_limit", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('BOOLEAN', 'LIMIT', 'QUOTA')", name=op.f("ck_feature_feature_kind_valid")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_feature")),
    )
    op.create_table(
        "outbox_event",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("event_version", sa.SmallInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'DEAD')",
            name=op.f("ck_outbox_event_outbox_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
    )
    op.create_index(
        "ix_outbox_pending",
        "outbox_event",
        ["available_at", "id"],
        unique=False,
        postgresql_where="status = 'PENDING'",
    )
    op.create_index(
        "ix_outbox_status_created", "outbox_event", ["status", "occurred_at"], unique=False
    )
    op.create_table(
        "plan",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
        sa.UniqueConstraint("key", name="uq_plan_key"),
    )
    op.create_table(
        "processed_event",
        sa.Column("handler_name", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("handler_name", "event_id", name=op.f("pk_processed_event")),
    )
    op.create_table(
        "entitlement",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("feature_key", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('PLAN', 'OVERRIDE', 'TRIAL', 'PROMO')",
            name=op.f("ck_entitlement_entitlement_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_key"],
            ["feature.key"],
            name=op.f("fk_entitlement_feature_key_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_entitlement_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlement")),
    )
    op.create_index(
        "ix_entitlement_tenant", "entitlement", ["tenant_id", "feature_key"], unique=False
    )
    op.create_table(
        "plan_version",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
            name=op.f("fk_plan_version_plan_id_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_version")),
        sa.UniqueConstraint("plan_id", "version", name="uq_plan_version_plan_version"),
    )
    op.create_table(
        "plan_feature",
        sa.Column("plan_version_id", sa.UUID(), nullable=False),
        sa.Column("feature_key", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feature_key"],
            ["feature.key"],
            name=op.f("fk_plan_feature_feature_key_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_version.id"],
            name=op.f("fk_plan_feature_plan_version_id_plan_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_version_id", "feature_key", name=op.f("pk_plan_feature")),
    )
    op.create_table(
        "plan_price",
        sa.Column("plan_version_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("provider_price_ref", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval IN ('MONTH', 'YEAR')",
            name=op.f("ck_plan_price_plan_price_interval_valid"),
        ),
        sa.CheckConstraint(
            "amount_minor >= 0", name=op.f("ck_plan_price_plan_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_version.id"],
            name=op.f("fk_plan_price_plan_version_id_plan_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_price")),
        sa.UniqueConstraint(
            "plan_version_id", "currency", "interval", name="uq_plan_price_unique"
        ),
    )
    op.create_table(
        "tenant_subscription",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("plan_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_subscription_ref", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('TRIALING', 'ACTIVE', 'PAST_DUE', 'PAUSED', 'CANCELLED')",
            name=op.f("ck_tenant_subscription_subscription_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_version.id"],
            name=op.f("fk_tenant_subscription_plan_version_id_plan_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_tenant_subscription_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_subscription")),
    )
    op.create_index(
        "ix_subscription_live",
        "tenant_subscription",
        ["tenant_id"],
        unique=False,
        postgresql_where="status IN ('TRIALING','ACTIVE','PAST_DUE')",
    )

    # --- audit_log partitions -------------------------------------------
    # A missing partition makes every audited write fail, so the current month
    # and the next three are created up front. `ensure_audit_partitions`, run
    # by the relay process, keeps the window rolling forward.
    for statement in partition_statements(months_ahead=3, today=date(2026, 8, 1)):
        op.execute(statement)
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON audit_log TO app_runtime, app_platform")

    # --- row level security ---------------------------------------------
    for statement in enable_all(RLS_TABLES):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)
    op.drop_index(
        "ix_subscription_live",
        table_name="tenant_subscription",
        postgresql_where="status IN ('TRIALING','ACTIVE','PAST_DUE')",
    )
    op.drop_table("tenant_subscription")
    op.drop_table("plan_price")
    op.drop_table("plan_feature")
    op.drop_table("plan_version")
    op.drop_index("ix_entitlement_tenant", table_name="entitlement")
    op.drop_table("entitlement")
    op.drop_table("processed_event")
    op.drop_table("plan")
    op.drop_index("ix_outbox_status_created", table_name="outbox_event")
    op.drop_index(
        "ix_outbox_pending", table_name="outbox_event", postgresql_where="status = 'PENDING'"
    )
    op.drop_table("outbox_event")
    op.drop_table("feature")
    op.drop_index("ix_audit_tenant_time", table_name="audit_log")
    op.drop_index("ix_audit_object", table_name="audit_log")
    op.drop_index("ix_audit_actor", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
