"""announcement and tickets

Revision ID: 5e229cbe4f42
Revises: b17b99727013
Created: 2026-08-14 20:29:13.810605+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5e229cbe4f42"
down_revision: str | None = "b17b99727013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "club_branding", sa.Column("announcement_text", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "club_branding",
        sa.Column(
            "announcement_is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "club_branding", sa.Column("tickets_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "club_branding", sa.Column("tickets_label", sa.String(length=48), nullable=True)
    )
    op.alter_column("club_branding", "announcement_is_active", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("club_branding", "tickets_label")
    op.drop_column("club_branding", "tickets_url")
    op.drop_column("club_branding", "announcement_is_active")
    op.drop_column("club_branding", "announcement_text")
    # ### end Alembic commands ###
