"""newsletter subscribers

Revision ID: afc313e23eb8
Revises: a3ed85bca15b
Created: 2026-08-15 06:41:03.367956+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["newsletter_subscriber"]
from sqlalchemy.dialects import postgresql

revision: str = "afc313e23eb8"
down_revision: str | None = "a3ed85bca15b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_subscriber",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_newsletter_subscriber_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_subscriber")),
        sa.UniqueConstraint("tenant_id", "club_id", "email", name="uq_subscriber_email"),
    )
    op.create_index(
        op.f("ix_newsletter_subscriber_tenant_id"),
        "newsletter_subscriber",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscriber_club", "newsletter_subscriber", ["tenant_id", "club_id"], unique=False
    )
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    op.drop_index("ix_subscriber_club", table_name="newsletter_subscriber")
    op.drop_index(
        op.f("ix_newsletter_subscriber_tenant_id"), table_name="newsletter_subscriber"
    )
    op.drop_table("newsletter_subscriber")
    # ### end Alembic commands ###
