"""configurable footer

Revision ID: addc1019f600
Revises: f8f687fe932a
Created: 2026-08-15 14:23:54.787586+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "addc1019f600"
down_revision: str | None = "f8f687fe932a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "club_branding", sa.Column("contact_email", sa.String(length=320), nullable=True)
    )
    op.add_column(
        "club_branding", sa.Column("contact_phone", sa.String(length=32), nullable=True)
    )
    op.add_column("club_branding", sa.Column("address", sa.Text(), nullable=True))
    op.add_column(
        "club_branding", sa.Column("legal_line", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "club_branding",
        sa.Column(
            "sponsors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            # Existing rows need a value before the column can be NOT NULL.
            server_default="[]",
        ),
    )
    op.add_column(
        "club_branding", sa.Column("sponsors_title", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("club_branding", "sponsors_title")
    op.drop_column("club_branding", "sponsors")
    op.drop_column("club_branding", "legal_line")
    op.drop_column("club_branding", "address")
    op.drop_column("club_branding", "contact_phone")
    op.drop_column("club_branding", "contact_email")
    # ### end Alembic commands ###
