"""match events

Revision ID: a52f50ca5df3
Revises: ed70627d8dc8
Created: 2026-08-15 09:43:02.590575+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "a52f50ca5df3"
down_revision: str | None = "ed70627d8dc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_event",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=True),
        sa.Column("minute", sa.SmallInteger(), nullable=True),
        sa.Column("extra_minute", sa.SmallInteger(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=64), nullable=True),
        sa.Column("player_name", sa.String(length=160), nullable=True),
        sa.Column("related_name", sa.String(length=160), nullable=True),
        sa.Column("comment", sa.String(length=240), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('GOAL', 'CARD', 'SUBSTITUTION', 'VAR')",
            name=op.f("ck_match_event_event_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["match.id"], name="fk_event_match", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_event")),
        sa.UniqueConstraint(
            "match_id",
            "minute",
            "kind",
            "player_name",
            name="uq_match_event_moment",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("ix_match_event_match", "match_event", ["match_id", "minute"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_event_match", table_name="match_event")
    op.drop_table("match_event")
    # ### end Alembic commands ###
