"""analytics geography

Revision ID: 7e27681dce9b
Revises: f9b44764b0f4
Created: 2026-08-15 16:22:50.388671+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7e27681dce9b"
down_revision: str | None = "f9b44764b0f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analytics_event", sa.Column("country", sa.String(length=2), nullable=True))
    op.add_column("analytics_event", sa.Column("city", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analytics_event", "city")
    op.drop_column("analytics_event", "country")
    # ### end Alembic commands ###
