"""supporter accounts

Revision ID: 35d0eebe12d7
Revises: 13f3854dbbc3
Created: 2026-08-15 12:18:18.621604+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["supporter"]
from sqlalchemy.dialects import postgresql

revision: str = "35d0eebe12d7"
down_revision: str | None = "13f3854dbbc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supporter",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("marketing_opt_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_supporter_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_supporter_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supporter")),
        sa.UniqueConstraint("tenant_id", "club_id", "user_id", name="uq_supporter_club_user"),
    )
    op.create_index(op.f("ix_supporter_tenant_id"), "supporter", ["tenant_id"], unique=False)
    op.create_index("ix_supporter_user", "supporter", ["user_id"], unique=False)
    op.add_column("shop_order", sa.Column("supporter_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    op.drop_column("shop_order", "supporter_id")
    op.drop_index("ix_supporter_user", table_name="supporter")
    op.drop_index(op.f("ix_supporter_tenant_id"), table_name="supporter")
    op.drop_table("supporter")
    # ### end Alembic commands ###
