"""shop catalogue and ordering kernel

Revision ID: 8fd39f9ceba3
Revises: b8164a3fa861
Created: 2026-08-14 21:31:16.257065+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

# Every table here is tenant-scoped, including the anonymous supporter's cart:
# a basket belongs to the club whose shop it was filled from.
RLS_TABLES = [
    "cart",
    "cart_line",
    "shop_order",
    "shop_order_line",
    "product",
    "product_variant",
]


revision: str = "8fd39f9ceba3"
down_revision: str | None = "b8164a3fa861"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'CONVERTED', 'ABANDONED')",
            name=op.f("ck_cart_cart_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_cart_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_cart_tenant_id_id"),
        sa.UniqueConstraint("token", name="uq_cart_token"),
    )
    op.create_index(
        "ix_cart_club_status", "cart", ["tenant_id", "club_id", "status"], unique=False
    )
    op.create_index(op.f("ix_cart_tenant_id"), "cart", ["tenant_id"], unique=False)
    op.create_table(
        "product",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cover_media_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "price_minor >= 0", name=op.f("ck_product_product_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_product_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("tenant_id", "club_id", "slug", name="uq_product_slug"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_product_tenant_id_id"),
    )
    op.create_index(
        "ix_product_club_active", "product", ["tenant_id", "club_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_product_tenant_id"), "product", ["tenant_id"], unique=False)
    op.create_table(
        "shop_order",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_minor", sa.Integer(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("buyer_name", sa.String(length=160), nullable=False),
        sa.Column("buyer_email", sa.String(length=320), nullable=True),
        sa.Column("buyer_phone", sa.String(length=32), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("payment_method", sa.String(length=16), nullable=False),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "payment_method IN ('ON_COLLECTION', 'CARD')",
            name=op.f("ck_shop_order_order_payment_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'AWAITING_COLLECTION', 'COLLECTED', 'CANCELLED')",
            name=op.f("ck_shop_order_order_status_valid"),
        ),
        sa.CheckConstraint(
            "total_minor >= 0", name=op.f("ck_shop_order_order_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_shop_order_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_order")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_order_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "reference", name="uq_order_reference"),
    )
    op.create_index(
        "ix_order_club_status", "shop_order", ["tenant_id", "club_id", "status"], unique=False
    )
    op.create_index(
        "ix_order_placed", "shop_order", ["tenant_id", "club_id", "placed_at"], unique=False
    )
    op.create_index(op.f("ix_shop_order_tenant_id"), "shop_order", ["tenant_id"], unique=False)
    op.create_table(
        "cart_line",
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("line_type", sa.String(length=16), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "line_type IN ('PRODUCT', 'TICKET', 'SEASON_TICKET', 'MEMBERSHIP', 'DONATION')",
            name=op.f("ck_cart_line_cart_line_type_valid"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_cart_line_cart_line_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cart_id"],
            ["cart.tenant_id", "cart.id"],
            name="fk_cart_line_cart",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_cart_line_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_line")),
        sa.UniqueConstraint(
            "cart_id", "line_type", "reference_id", name="uq_cart_line_reference"
        ),
    )
    op.create_index(op.f("ix_cart_line_tenant_id"), "cart_line", ["tenant_id"], unique=False)
    op.create_table(
        "product_variant",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=48), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "stock >= 0", name=op.f("ck_product_variant_variant_stock_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["product.tenant_id", "product.id"],
            name="fk_variant_product",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_product_variant_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variant")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_variant_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_product_variant_tenant_id"), "product_variant", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_variant_product", "product_variant", ["tenant_id", "product_id"], unique=False
    )
    op.create_table(
        "shop_order_line",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("line_type", sa.String(length=16), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "line_type IN ('PRODUCT', 'TICKET', 'SEASON_TICKET', 'MEMBERSHIP', 'DONATION')",
            name=op.f("ck_shop_order_line_order_line_type_valid"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_shop_order_line_order_line_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["shop_order.tenant_id", "shop_order.id"],
            name="fk_order_line_order",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_shop_order_line_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_order_line")),
    )
    op.create_index(
        op.f("ix_shop_order_line_tenant_id"), "shop_order_line", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    op.drop_index(op.f("ix_shop_order_line_tenant_id"), table_name="shop_order_line")
    op.drop_table("shop_order_line")
    op.drop_index("ix_variant_product", table_name="product_variant")
    op.drop_index(op.f("ix_product_variant_tenant_id"), table_name="product_variant")
    op.drop_table("product_variant")
    op.drop_index(op.f("ix_cart_line_tenant_id"), table_name="cart_line")
    op.drop_table("cart_line")
    op.drop_index(op.f("ix_shop_order_tenant_id"), table_name="shop_order")
    op.drop_index("ix_order_placed", table_name="shop_order")
    op.drop_index("ix_order_club_status", table_name="shop_order")
    op.drop_table("shop_order")
    op.drop_index(op.f("ix_product_tenant_id"), table_name="product")
    op.drop_index("ix_product_club_active", table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_cart_tenant_id"), table_name="cart")
    op.drop_index("ix_cart_club_status", table_name="cart")
    op.drop_table("cart")
    # ### end Alembic commands ###
