"""club branding

Revision ID: 3043c5982317
Revises: 5a7c2e918d64
Created: 2026-08-13 21:22:37.223871+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.rls import disable, enable

revision: str = "3043c5982317"
down_revision: str | None = "5a7c2e918d64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_branding",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("template", sa.String(length=16), nullable=False),
        sa.Column("color_mode", sa.String(length=8), nullable=False),
        sa.Column("color_primary", sa.String(length=7), nullable=False),
        sa.Column("color_secondary", sa.String(length=7), nullable=True),
        sa.Column("color_accent", sa.String(length=7), nullable=True),
        sa.Column("tagline", sa.String(length=160), nullable=True),
        sa.Column("social", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "color_mode IN ('LIGHT', 'DARK', 'AUTO')",
            name=op.f("ck_club_branding_club_branding_color_mode_valid"),
        ),
        sa.CheckConstraint(
            "color_primary ~ '^#[0-9A-F]{6}$'",
            name=op.f("ck_club_branding_club_branding_primary_is_hex"),
        ),
        sa.CheckConstraint(
            "template IN ('CLASSIC', 'BOLD', 'COMPACT', 'EDITORIAL')",
            name=op.f("ck_club_branding_club_branding_template_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "club_id"],
            ["club.tenant_id", "club.id"],
            name="fk_club_branding_club",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_club_branding_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("club_id", name=op.f("pk_club_branding")),
    )
    op.create_index(
        op.f("ix_club_branding_tenant_id"), "club_branding", ["tenant_id"], unique=False
    )

    # Backfill from the colours that lived on `club`, then remove them. One
    # source of truth: two places holding a club's primary colour is how they
    # drift. Safe to do in a single migration only because nothing is in
    # production yet — after launch this is an expand/migrate/contract sequence
    # across three releases (ADR-0010).
    op.execute(
        """
        INSERT INTO club_branding
            (club_id, tenant_id, template, color_mode, color_primary,
             color_secondary, created_at, updated_at)
        SELECT id, tenant_id, 'CLASSIC', 'LIGHT',
               COALESCE(upper(color_primary), '#1F4B99'),
               upper(color_secondary),
               now(), now()
        FROM club
        ON CONFLICT (club_id) DO NOTHING
        """
    )
    op.drop_column("club", "color_primary")
    op.drop_column("club", "color_secondary")

    for statement in enable("club_branding"):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column("club", sa.Column("color_primary", sa.String(length=7), nullable=True))
    op.add_column("club", sa.Column("color_secondary", sa.String(length=7), nullable=True))
    op.execute(
        """
        UPDATE club c SET color_primary = b.color_primary,
                          color_secondary = b.color_secondary
        FROM club_branding b WHERE b.club_id = c.id
        """
    )
    for statement in disable("club_branding"):
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_club_branding_tenant_id"), table_name="club_branding")
    op.drop_table("club_branding")
    # ### end Alembic commands ###
