"""club history and profile

Revision ID: c1f01629f9b8
Revises: a52f50ca5df3
Created: 2026-08-15 09:49:40.150274+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "c1f01629f9b8"
down_revision: str | None = "a52f50ca5df3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_season_record",
        sa.Column("directory_club_id", sa.UUID(), nullable=False),
        sa.Column("competition_season_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=True),
        sa.Column("played", sa.SmallInteger(), nullable=False),
        sa.Column("won", sa.SmallInteger(), nullable=False),
        sa.Column("drawn", sa.SmallInteger(), nullable=False),
        sa.Column("lost", sa.SmallInteger(), nullable=False),
        sa.Column("goals_for", sa.SmallInteger(), nullable=False),
        sa.Column("goals_against", sa.SmallInteger(), nullable=False),
        sa.Column("points", sa.SmallInteger(), nullable=False),
        sa.Column("outcome", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_season_record")),
        sa.UniqueConstraint(
            "directory_club_id", "competition_season_id", name="uq_club_season_record"
        ),
    )
    op.create_index(
        "ix_club_season_record_club", "club_season_record", ["directory_club_id"], unique=False
    )
    op.add_column(
        "directory_club", sa.Column("venue_name", sa.String(length=160), nullable=True)
    )
    op.add_column("directory_club", sa.Column("venue_capacity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("directory_club", "venue_capacity")
    op.drop_column("directory_club", "venue_name")
    op.drop_index("ix_club_season_record_club", table_name="club_season_record")
    op.drop_table("club_season_record")
    # ### end Alembic commands ###
