"""api football integration

Revision ID: 83f7a572116c
Revises: afc313e23eb8
Created: 2026-08-15 08:36:37.683259+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "83f7a572116c"
down_revision: str | None = "afc313e23eb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_link",
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("local_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_link")),
        sa.UniqueConstraint(
            "provider", "entity_type", "local_id", name="uq_provider_link_local"
        ),
        sa.UniqueConstraint(
            "provider", "entity_type", "provider_id", name="uq_provider_link_remote"
        ),
    )
    op.create_index(
        "ix_provider_link_lookup",
        "provider_link",
        ["provider", "entity_type", "provider_id"],
        unique=False,
    )
    op.create_table(
        "provider_sync_run",
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("competition_season_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_sync_run")),
    )
    op.create_index(
        "ix_sync_run_recent", "provider_sync_run", ["provider", "started_at"], unique=False
    )
    # Every existing fixture was entered by a club. server_default backfills
    # them and is then dropped, so the column stays explicit in new inserts.
    op.add_column(
        "match",
        sa.Column("source", sa.String(length=16), nullable=False, server_default="CLUB"),
    )
    op.alter_column("match", "source", server_default=None)
    op.add_column("match", sa.Column("minute", sa.SmallInteger(), nullable=True))

    # Autogenerate does not see CHECK changes. LIVE now carries a score, and
    # `source` needs its own constraint — without these the column exists and
    # the first live update is rejected by the database.
    op.execute(
        "ALTER TABLE match DROP CONSTRAINT ck_match_match_score_matches_status"
    )
    op.execute(
        "ALTER TABLE match ADD CONSTRAINT ck_match_match_score_matches_status "
        "CHECK ((status IN ('FINISHED', 'AWARDED', 'LIVE')) = "
        "(home_score IS NOT NULL AND away_score IS NOT NULL))"
    )
    op.create_check_constraint(
        op.f("ck_match_match_source_valid"), "match", "source IN ('CLUB', 'API_FOOTBALL')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_match_match_source_valid"), "match", type_="check")
    op.execute("ALTER TABLE match DROP CONSTRAINT ck_match_match_score_matches_status")
    op.execute(
        "ALTER TABLE match ADD CONSTRAINT ck_match_match_score_matches_status "
        "CHECK ((status IN ('FINISHED', 'AWARDED')) = "
        "(home_score IS NOT NULL AND away_score IS NOT NULL))"
    )
    op.drop_column("match", "minute")
    op.drop_column("match", "source")
    op.drop_index("ix_sync_run_recent", table_name="provider_sync_run")
    op.drop_table("provider_sync_run")
    op.drop_index("ix_provider_link_lookup", table_name="provider_link")
    op.drop_table("provider_link")
    # ### end Alembic commands ###
