"""standings published at

Revision ID: 13f3854dbbc3
Revises: 65b5920b3068
Created: 2026-08-15 12:06:25.607771+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "13f3854dbbc3"
down_revision: str | None = "65b5920b3068"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "club_season_record",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("club_season_record", "published_at")
    # ### end Alembic commands ###
