"""club entered match events

Revision ID: 5d0cd4541be4
Revises: 6a7f9a72c2d0
Created: 2026-08-18 15:12:22.855275+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "5d0cd4541be4"
down_revision: str | None = "6a7f9a72c2d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_event",
        sa.Column("source", sa.String(length=8), nullable=False, server_default="PROVIDER"),
    )
    op.create_check_constraint(
        op.f("ck_match_event_event_source_valid"),
        "match_event",
        "source IN ('PROVIDER', 'CLUB')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_match_event_event_source_valid"), "match_event", type_="check")
    op.drop_column("match_event", "source")
    # ### end Alembic commands ###
