"""sport per team club tenant and competition

Revision ID: f8f687fe932a
Revises: 225d0fbd5755
Created: 2026-08-15 13:20:24.629786+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "f8f687fe932a"
down_revision: str | None = "225d0fbd5755"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "club",
        sa.Column("sport", sa.String(length=24), server_default="FOOTBALL", nullable=False),
    )
    op.add_column(
        "competition",
        sa.Column("sport", sa.String(length=24), server_default="FOOTBALL", nullable=False),
    )
    op.add_column(
        "team",
        sa.Column("sport", sa.String(length=24), server_default="FOOTBALL", nullable=False),
    )
    op.add_column(
        "tenant",
        sa.Column("sport", sa.String(length=24), server_default="FOOTBALL", nullable=False),
    )
    # ### end Alembic commands ###

    # Positions are now every sport's vocabulary, and "UNIVERSAL" does not fit
    # in four characters.
    op.alter_column(
        "player", "primary_position", type_=sa.String(length=12), existing_nullable=True
    )
    op.alter_column(
        "player",
        "secondary_positions",
        type_=sa.ARRAY(sa.String(length=12)),
        existing_nullable=False,
    )

    # A CHECK constraint's *contents* changing is invisible to autogenerate, so
    # the widened event vocabulary is written by hand. A handball suspension and
    # a rugby try have to be storable before either sport can be entered.
    op.execute("ALTER TABLE match_event DROP CONSTRAINT ck_match_event_event_kind_valid")
    op.execute(
        "ALTER TABLE match_event ADD CONSTRAINT ck_match_event_event_kind_valid "
        "CHECK (kind IN ('GOAL', 'CARD', 'SUBSTITUTION', 'VAR', 'SUSPENSION', "
        "'SCORE', 'FOUL', 'SET', 'TRY', 'CONVERSION', 'PENALTY', 'EXCLUSION'))"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE match_event DROP CONSTRAINT ck_match_event_event_kind_valid")
    op.execute(
        "ALTER TABLE match_event ADD CONSTRAINT ck_match_event_event_kind_valid "
        "CHECK (kind IN ('GOAL', 'CARD', 'SUBSTITUTION', 'VAR'))"
    )
    op.alter_column(
        "player", "primary_position", type_=sa.String(length=4), existing_nullable=True
    )
    op.alter_column(
        "player",
        "secondary_positions",
        type_=sa.ARRAY(sa.String(length=4)),
        existing_nullable=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant", "sport")
    op.drop_column("team", "sport")
    op.drop_column("competition", "sport")
    op.drop_column("club", "sport")
    # ### end Alembic commands ###
