"""player photo and media purpose

Revision ID: a3ed85bca15b
Revises: 8fd39f9ceba3
Created: 2026-08-15 06:12:12.690675+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "a3ed85bca15b"
down_revision: str | None = "8fd39f9ceba3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("photo_media_id", sa.UUID(), nullable=True))

    # Autogenerate does not see CHECK constraint changes, so the new purpose has
    # to be spelled out — without this the column exists and every upload for it
    # is rejected by the database.
    op.execute(
        "ALTER TABLE media_asset DROP CONSTRAINT ck_media_asset_media_purpose_valid"
    )
    op.execute(
        "ALTER TABLE media_asset ADD CONSTRAINT ck_media_asset_media_purpose_valid "
        "CHECK (purpose IN ('CREST', 'HERO', 'PARTNER_LOGO', 'COMPETITION_BADGE', "
        "'ARTICLE_IMAGE', 'TEAM_PHOTO', 'PLAYER_PHOTO'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE media_asset DROP CONSTRAINT ck_media_asset_media_purpose_valid"
    )
    op.execute(
        "ALTER TABLE media_asset ADD CONSTRAINT ck_media_asset_media_purpose_valid "
        "CHECK (purpose IN ('CREST', 'HERO', 'PARTNER_LOGO', 'COMPETITION_BADGE', "
        "'ARTICLE_IMAGE', 'TEAM_PHOTO'))"
    )
    op.drop_column("player", "photo_media_id")
    # ### end Alembic commands ###
