"""team staff

Revision ID: 225d0fbd5755
Revises: 35d0eebe12d7
Created: 2026-08-15 13:07:05.306256+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import disable_all, enable_all

RLS_TABLES = ["team_staff"]


revision: str = "225d0fbd5755"
down_revision: str | None = "35d0eebe12d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_staff",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=True),
        sa.Column("photo_media_id", sa.UUID(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "role IN ('HEAD_COACH', 'ASSISTANT_COACH', 'GOALKEEPING_COACH', 'FITNESS_COACH', 'ANALYST', 'PHYSIO', 'DOCTOR', 'TEAM_MANAGER', 'KIT_MANAGER')",
            name=op.f("ck_team_staff_team_staff_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["person.tenant_id", "person.id"],
            name="fk_team_staff_person",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "team_id"],
            ["team.tenant_id", "team.id"],
            name="fk_team_staff_team",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_team_staff_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_staff")),
        sa.UniqueConstraint("tenant_id", "team_id", "person_id", name="uq_team_staff_person"),
    )
    op.create_index("ix_team_staff_team", "team_staff", ["tenant_id", "team_id"], unique=False)
    op.create_index(op.f("ix_team_staff_tenant_id"), "team_staff", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    for statement in enable_all(RLS_TABLES):
        op.execute(statement)


def downgrade() -> None:
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_staff_tenant_id"), table_name="team_staff")
    op.drop_index("ix_team_staff_team", table_name="team_staff")
    op.drop_table("team_staff")
    # ### end Alembic commands ###
