"""club can correct a round label

Revision ID: 6a7f9a72c2d0
Revises: b6a8db0842a0
Created: 2026-08-18 15:09:28.906882+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "6a7f9a72c2d0"
down_revision: str | None = "b6a8db0842a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "club_branding",
        "lineup_display",
        existing_type=sa.VARCHAR(length=8),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "match", sa.Column("round_label_override", sa.String(length=48), nullable=True)
    )
    op.drop_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_bd5c"),
        "venue_configuration",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_matches_status"),
        "venue_configuration",
        "(status = 'DRAFT') = (published_at IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_matches_status"),
        "venue_configuration",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_bd5c"),
        "venue_configuration",
        "(status::text = 'DRAFT'::text) = (published_at IS NULL)",
    )
    op.drop_column("match", "round_label_override")
    op.alter_column(
        "club_branding",
        "lineup_display",
        existing_type=sa.VARCHAR(length=8),
        server_default=sa.text("'LIST'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
