"""initial schema

Revision ID: 75b1d44988b4
Revises:
Created: 2026-08-13 20:30:12.979061+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '75b1d44988b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_permission'))
    )
    op.create_table('tenant',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('default_locale', sa.String(length=10), nullable=False),
    sa.Column('supported_locales', postgresql.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('billing_email', postgresql.CITEXT(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED')", name=op.f('ck_tenant_tenant_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenant_slug'))
    )
    op.create_index('ix_tenant_status', 'tenant', ['status'], unique=False)
    op.create_table('user_account',
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_platform_user', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name='uq_user_account_email'),
    sa.UniqueConstraint('subject_id', name='uq_user_account_subject_id')
    )
    op.create_table('club',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('default_locale', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('color_primary', sa.String(length=7), nullable=True),
    sa.Column('color_secondary', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'ARCHIVED')", name=op.f('ck_club_club_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_club_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_club_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_club_tenant_id_slug')
    )
    op.create_index(op.f('ix_club_tenant_id'), 'club', ['tenant_id'], unique=False)
    op.create_table('person',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nationality', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_locale', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source IN ('STAFF_ENTRY', 'SELF_REGISTRATION', 'IMPORT', 'DEMO')", name=op.f('ck_person_person_source_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_person_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_person_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_person_tenant_id_id')
    )
    op.create_index('ix_person_email', 'person', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_person_name', 'person', ['tenant_id', 'last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_person_tenant_id'), 'person', ['tenant_id'], unique=False)
    op.create_index('uq_person_tenant_user', 'person', ['tenant_id', 'user_id'], unique=True, postgresql_where='user_id IS NOT NULL')
    op.create_table('role',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_level', sa.String(length=16), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_assignable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_level IN ('PLATFORM', 'TENANT', 'CLUB', 'TEAM')", name=op.f('ck_role_role_scope_level_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_role_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_index('uq_role_tenant_key', 'role', ['tenant_id', 'key'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('club_domain',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('hostname', postgresql.CITEXT(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name=op.f('fk_club_domain_club_id_club'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_club_domain_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_domain')),
    sa.UniqueConstraint('hostname', name='uq_club_domain_hostname')
    )
    op.create_index('ix_club_domain_club', 'club_domain', ['tenant_id', 'club_id'], unique=False)
    op.create_index(op.f('ix_club_domain_tenant_id'), 'club_domain', ['tenant_id'], unique=False)
    op.create_table('person_role_flag',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role_kind', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_kind IN ('PLAYER', 'STAFF', 'GUARDIAN', 'FAN', 'MEMBER', 'PROSPECT')", name=op.f('ck_person_role_flag_person_role_kind_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['person.tenant_id', 'person.id'], name='fk_person_role_flag_person', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_person_role_flag_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('person_id', 'role_kind', 'tenant_id', name=op.f('pk_person_role_flag'))
    )
    op.create_table('player',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('primary_position', sa.String(length=4), nullable=True),
    sa.Column('secondary_positions', postgresql.ARRAY(sa.String(length=4)), nullable=False),
    sa.Column('preferred_foot', sa.String(length=8), nullable=True),
    sa.Column('federation_id', sa.String(length=64), nullable=True),
    sa.Column('joined_club_on', sa.Date(), nullable=True),
    sa.Column('left_club_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("preferred_foot IS NULL OR preferred_foot IN ('LEFT', 'RIGHT', 'BOTH')", name=op.f('ck_player_player_foot_valid')),
    sa.CheckConstraint("status IN ('TRIAL', 'REGISTERED', 'LOANED_OUT', 'INACTIVE', 'DEPARTED')", name=op.f('ck_player_player_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'club_id'], ['club.tenant_id', 'club.id'], name='fk_player_club', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['person.tenant_id', 'person.id'], name='fk_player_person', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_player_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('tenant_id', 'club_id', 'person_id', name='uq_player_person_club'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_player_tenant_id_id')
    )
    op.create_index('ix_player_club_status', 'player', ['tenant_id', 'club_id', 'status'], unique=False)
    op.create_index(op.f('ix_player_tenant_id'), 'player', ['tenant_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['permission.key'], name=op.f('fk_role_permission_permission_key_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_key', name=op.f('pk_role_permission'))
    )
    op.create_table('season',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_season_season_dates_ordered')),
    sa.ForeignKeyConstraint(['tenant_id', 'club_id'], ['club.tenant_id', 'club.id'], name='fk_season_club', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_season_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season')),
    sa.UniqueConstraint('tenant_id', 'club_id', 'name', name='uq_season_club_name'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_season_tenant_id_id')
    )
    op.create_index(op.f('ix_season_tenant_id'), 'season', ['tenant_id'], unique=False)
    op.create_index('uq_season_current_per_club', 'season', ['club_id'], unique=True, postgresql_where='is_current')
    op.create_table('team',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('is_academy', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("gender IN ('MALE', 'FEMALE', 'MIXED')", name=op.f('ck_team_team_gender_valid')),
    sa.CheckConstraint("level IN ('FIRST', 'RESERVE', 'YOUTH', 'FUTSAL', 'OTHER')", name=op.f('ck_team_team_level_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'club_id'], ['club.tenant_id', 'club.id'], name='fk_team_club', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_team_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('tenant_id', 'club_id', 'code', name='uq_team_club_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_team_tenant_id_id')
    )
    op.create_index('ix_team_club', 'team', ['tenant_id', 'club_id'], unique=False)
    op.create_index(op.f('ix_team_tenant_id'), 'team', ['tenant_id'], unique=False)
    op.create_table('player_registration',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('shirt_number', sa.SmallInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('registered_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('ended_reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("kind IN ('PERMANENT', 'LOAN', 'DUAL', 'TRIAL')", name=op.f('ck_player_registration_registration_kind_valid')),
    sa.CheckConstraint('shirt_number IS NULL OR (shirt_number BETWEEN 1 AND 99)', name=op.f('ck_player_registration_registration_shirt_range')),
    sa.ForeignKeyConstraint(['tenant_id', 'player_id'], ['player.tenant_id', 'player.id'], name='fk_registration_player', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['season.tenant_id', 'season.id'], name='fk_registration_season', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'team_id'], ['team.tenant_id', 'team.id'], name='fk_registration_team', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_player_registration_tenant_id_tenant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_registration'))
    )
    op.create_index(op.f('ix_player_registration_tenant_id'), 'player_registration', ['tenant_id'], unique=False)
    op.create_index('ix_registration_team_active', 'player_registration', ['tenant_id', 'team_id', 'season_id'], unique=False, postgresql_where='ended_on IS NULL')
    op.create_index('uq_registration_active', 'player_registration', ['player_id', 'team_id', 'season_id'], unique=True, postgresql_where='ended_on IS NULL')
    op.create_index('uq_registration_shirt', 'player_registration', ['team_id', 'season_id', 'shirt_number'], unique=True, postgresql_where='ended_on IS NULL AND shirt_number IS NOT NULL')
    op.create_table('role_assignment',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name=op.f('fk_role_assignment_club_id_club'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_assignment_role_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_role_assignment_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_role_assignment_tenant_id_tenant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_role_assignment_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignment')),
    sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', 'club_id', 'team_id', name='uq_role_assignment_unique_grant', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_role_assignment_active', 'role_assignment', ['user_id', 'tenant_id'], unique=False, postgresql_where='revoked_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_assignment_active', table_name='role_assignment', postgresql_where='revoked_at IS NULL')
    op.drop_table('role_assignment')
    op.drop_index('uq_registration_shirt', table_name='player_registration', postgresql_where='ended_on IS NULL AND shirt_number IS NOT NULL')
    op.drop_index('uq_registration_active', table_name='player_registration', postgresql_where='ended_on IS NULL')
    op.drop_index('ix_registration_team_active', table_name='player_registration', postgresql_where='ended_on IS NULL')
    op.drop_index(op.f('ix_player_registration_tenant_id'), table_name='player_registration')
    op.drop_table('player_registration')
    op.drop_index(op.f('ix_team_tenant_id'), table_name='team')
    op.drop_index('ix_team_club', table_name='team')
    op.drop_table('team')
    op.drop_index('uq_season_current_per_club', table_name='season', postgresql_where='is_current')
    op.drop_index(op.f('ix_season_tenant_id'), table_name='season')
    op.drop_table('season')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_player_tenant_id'), table_name='player')
    op.drop_index('ix_player_club_status', table_name='player')
    op.drop_table('player')
    op.drop_table('person_role_flag')
    op.drop_index(op.f('ix_club_domain_tenant_id'), table_name='club_domain')
    op.drop_index('ix_club_domain_club', table_name='club_domain')
    op.drop_table('club_domain')
    op.drop_index('uq_role_tenant_key', table_name='role', postgresql_nulls_not_distinct=True)
    op.drop_table('role')
    op.drop_index('uq_person_tenant_user', table_name='person', postgresql_where='user_id IS NOT NULL')
    op.drop_index(op.f('ix_person_tenant_id'), table_name='person')
    op.drop_index('ix_person_name', table_name='person')
    op.drop_index('ix_person_email', table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_club_tenant_id'), table_name='club')
    op.drop_table('club')
    op.drop_table('user_account')
    op.drop_index('ix_tenant_status', table_name='tenant')
    op.drop_table('tenant')
    op.drop_table('permission')
    # ### end Alembic commands ###
