"""match lineups

Revision ID: b6a8db0842a0
Revises: 2c20579e61d9
Created: 2026-08-18 14:18:28.159477+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6a8db0842a0"
down_revision: str | None = "2c20579e61d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_lineup",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("formation", sa.String(length=16), nullable=True),
        sa.Column("coach_name", sa.String(length=160), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("arranged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "side IN ('HOME', 'AWAY')", name=op.f("ck_match_lineup_lineup_side_valid")
        ),
        sa.CheckConstraint(
            "source IN ('PROVIDER', 'CLUB')", name=op.f("ck_match_lineup_lineup_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["match.id"], name="fk_lineup_match", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_lineup")),
        sa.UniqueConstraint("match_id", "side", name="uq_lineup_match_side"),
    )
    op.create_table(
        "match_lineup_player",
        sa.Column("lineup_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("shirt_number", sa.SmallInteger(), nullable=True),
        sa.Column("position", sa.String(length=1), nullable=True),
        sa.Column("grid", sa.String(length=8), nullable=True),
        sa.Column("is_starter", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position IS NULL OR position IN ('G', 'D', 'M', 'F')",
            name=op.f("ck_match_lineup_player_lineup_player_position_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["lineup_id"],
            ["match_lineup.id"],
            name="fk_lineup_player_lineup",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_lineup_player")),
    )
    op.create_index(
        "ix_lineup_player_lineup",
        "match_lineup_player",
        ["lineup_id", "is_starter"],
        unique=False,
    )
    op.create_index(
        "uq_lineup_player_grid",
        "match_lineup_player",
        ["lineup_id", "grid"],
        unique=True,
        postgresql_where=sa.text("grid IS NOT NULL"),
    )
    op.alter_column(
        "payment_attempt",
        "state",
        existing_type=sa.VARCHAR(length=24),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("fk_payment_attempt_order"), "payment_attempt", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_payment_attempt_tenant_id_tenant"),
        "payment_attempt",
        "tenant",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "payment_credential",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "payment_credential",
        "is_live",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("fk_payment_credential_tenant_id_tenant"),
        "payment_credential",
        "tenant",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "payment_provider_call",
        "ok",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "payment_provider_call",
        "sent",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "payment_provider_call",
        "received",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("fk_payment_provider_call_tenant_id_tenant"),
        "payment_provider_call",
        "tenant",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_bd5c"),
        "venue_configuration",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_matches_status"),
        "venue_configuration",
        "(status = 'DRAFT') = (published_at IS NULL)",
    )
    # ### end Alembic commands ###


    # How each club wants a team sheet presented. Defaults to the list, which
    # is what the provider's data supports everywhere; a club that arranges its
    # eleven on a pitch switches it.
    op.add_column(
        "club_branding",
        sa.Column(
            "lineup_display",
            sa.String(length=8),
            nullable=False,
            server_default="LIST",
        ),
    )
    op.create_check_constraint(
        "lineup_display_valid",
        "club_branding",
        "lineup_display IN ('LIST', 'PITCH')",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tolerant, because this migration grew the column after an earlier run of
    # itself had already created the tables above.
    op.execute(
        "ALTER TABLE club_branding DROP CONSTRAINT IF EXISTS ck_club_branding_lineup_display_valid"
    )
    op.execute("ALTER TABLE club_branding DROP COLUMN IF EXISTS lineup_display")
    op.drop_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_matches_status"),
        "venue_configuration",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_venue_configuration_venue_configuration_published_at_bd5c"),
        "venue_configuration",
        "(status::text = 'DRAFT'::text) = (published_at IS NULL)",
    )
    op.drop_constraint(
        op.f("fk_payment_provider_call_tenant_id_tenant"),
        "payment_provider_call",
        type_="foreignkey",
    )
    op.alter_column(
        "payment_provider_call",
        "received",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_provider_call",
        "sent",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_provider_call",
        "ok",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_payment_credential_tenant_id_tenant"), "payment_credential", type_="foreignkey"
    )
    op.alter_column(
        "payment_credential",
        "is_live",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_credential",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_payment_attempt_tenant_id_tenant"), "payment_attempt", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_payment_attempt_order"),
        "payment_attempt",
        "shop_order",
        ["tenant_id", "order_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "payment_attempt",
        "state",
        existing_type=sa.VARCHAR(length=24),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(
        "uq_lineup_player_grid",
        table_name="match_lineup_player",
        postgresql_where=sa.text("grid IS NOT NULL"),
    )
    op.drop_index("ix_lineup_player_lineup", table_name="match_lineup_player")
    op.drop_table("match_lineup_player")
    op.drop_table("match_lineup")
    # ### end Alembic commands ###
