"""stadium and ticketing

Revision ID: c50270051936
Revises: c4e91a7b0d38
Created: 2026-08-17 18:13:01.514319+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.rls import disable_all, enable_all

revision: str = "c50270051936"
down_revision: str | None = "c4e91a7b0d38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table here belongs to exactly one club, so every one of them gets a
# forced RLS policy. The sweep in tests/isolation/test_rls_sweep.py compares
# this list against the live database and fails if a tenant-scoped table has
# been added without one — which is the only reason a list this long is safe
# to maintain by hand.
RLS_TABLES = [
    "venue",
    "venue_configuration",
    "price_zone",
    "stand",
    "section",
    "seat_row",
    "seat",
    "access_zone",
    "gate",
    "gate_section",
    "ticket_type",
    "ticketed_event",
    "event_configuration_snapshot",
    "event_seat_inventory",
    "allocation",
    "price_list",
    "price_rule",
    "promo_code",
    "season_ticket_product",
    "season_ticket_event",
    "season_pass",
    "event_entitlement",
    "ticket",
    "access_credential",
    "scanner_device",
    "device_enrollment",
    "gate_assignment",
    "access_rule",
    "scan_log",
]



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_list",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=12), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=True),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'VENUE' AND venue_id IS NOT NULL AND season_id IS NULL   AND event_id IS NULL) OR (scope = 'SEASON' AND season_id IS NOT NULL AND event_id IS NULL) OR (scope = 'EVENT' AND event_id IS NOT NULL)",
            name=op.f("ck_price_list_price_list_anchor_matches_scope"),
        ),
        sa.CheckConstraint(
            "scope IN ('VENUE', 'SEASON', 'EVENT')",
            name=op.f("ck_price_list_price_list_scope_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_price_list_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_list")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_price_list_tenant_id_id"),
    )
    op.create_index(
        "ix_price_list_lookup",
        "price_list",
        ["tenant_id", "scope", "event_id", "season_id", "venue_id"],
        unique=False,
    )
    op.create_index(op.f("ix_price_list_tenant_id"), "price_list", ["tenant_id"], unique=False)
    op.create_table(
        "promo_code",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("discount_kind", sa.String(length=16), nullable=False),
        sa.Column("discount_value", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "discount_kind IN ('PERCENTAGE', 'FIXED_AMOUNT')",
            name=op.f("ck_promo_code_promo_discount_valid"),
        ),
        sa.CheckConstraint(
            "discount_value >= 0", name=op.f("ck_promo_code_promo_discount_non_negative")
        ),
        sa.CheckConstraint(
            "max_redemptions IS NULL OR max_redemptions > 0",
            name=op.f("ck_promo_code_promo_max_redemptions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_promo_code_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_code")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_promo_code"),
    )
    op.create_index(op.f("ix_promo_code_tenant_id"), "promo_code", ["tenant_id"], unique=False)
    op.create_table(
        "scanner_device",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("device_code", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACTIVE', 'REVOKED')",
            name=op.f("ck_scanner_device_scanner_device_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_scanner_device_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scanner_device")),
        sa.UniqueConstraint("tenant_id", "device_code", name="uq_scanner_device_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_scanner_device_tenant_id_id"),
    )
    op.create_index(
        "ix_scanner_device_status", "scanner_device", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_scanner_device_tenant_id"), "scanner_device", ["tenant_id"], unique=False
    )
    op.create_table(
        "ticket_type",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=True),
        sa.Column("requires_proof", sa.Boolean(), nullable=False),
        sa.Column("is_complimentary", sa.Boolean(), nullable=False),
        sa.Column("is_away", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ticket_type_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_type")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_ticket_type_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_ticket_type_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_ticket_type_tenant_id"), "ticket_type", ["tenant_id"], unique=False
    )
    op.create_table(
        "venue",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("address", sa.String(length=240), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_capacity", sa.Integer(), nullable=False),
        sa.Column("pitch_orientation", sa.String(length=24), nullable=False),
        sa.Column("cover_media_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "pitch_orientation IN ('NORTH_SOUTH', 'NORTHEAST_SOUTHWEST', 'EAST_WEST', 'NORTHWEST_SOUTHEAST')",
            name=op.f("ck_venue_venue_pitch_orientation_valid"),
        ),
        sa.CheckConstraint(
            "expected_capacity >= 0", name=op.f("ck_venue_venue_capacity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_venue_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_venue_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_venue_tenant_id_id"),
    )
    op.create_index("ix_venue_club", "venue", ["tenant_id", "club_id"], unique=False)
    op.create_index(op.f("ix_venue_tenant_id"), "venue", ["tenant_id"], unique=False)
    op.create_table(
        "device_enrollment",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("enrollment_code", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "device_id"],
            ["scanner_device.tenant_id", "scanner_device.id"],
            name="fk_device_enrollment_device",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_device_enrollment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_enrollment")),
        sa.UniqueConstraint("enrollment_code", name="uq_device_enrollment_code"),
        sa.UniqueConstraint("token_hash", name="uq_device_enrollment_token"),
    )
    op.create_index(
        "ix_device_enrollment_device",
        "device_enrollment",
        ["tenant_id", "device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_enrollment_tenant_id"), "device_enrollment", ["tenant_id"], unique=False
    )
    op.create_table(
        "price_rule",
        sa.Column("price_list_id", sa.UUID(), nullable=False),
        sa.Column("ticket_type_id", sa.UUID(), nullable=False),
        sa.Column("price_zone_code", sa.String(length=24), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("vat_rate_bp", sa.Integer(), nullable=False),
        sa.Column("vat_included", sa.Boolean(), nullable=False),
        sa.Column("fee_minor", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "amount_minor >= 0", name=op.f("ck_price_rule_price_rule_amount_non_negative")
        ),
        sa.CheckConstraint(
            "vat_rate_bp >= 0 AND vat_rate_bp <= 10000",
            name=op.f("ck_price_rule_price_rule_vat_rate_sane"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "price_list_id"],
            ["price_list.tenant_id", "price_list.id"],
            name="fk_price_rule_list",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ticket_type_id"],
            ["ticket_type.tenant_id", "ticket_type.id"],
            name="fk_price_rule_ticket_type",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_price_rule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_rule")),
        sa.UniqueConstraint(
            "price_list_id", "price_zone_code", "ticket_type_id", name="uq_price_rule_cell"
        ),
    )
    op.create_index(op.f("ix_price_rule_tenant_id"), "price_rule", ["tenant_id"], unique=False)
    op.create_table(
        "venue_configuration",
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("total_capacity", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("forked_from_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(status = 'DRAFT') = (published_at IS NULL)",
            name=op.f("ck_venue_configuration_venue_configuration_published_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')",
            name=op.f("ck_venue_configuration_venue_configuration_status_valid"),
        ),
        sa.CheckConstraint(
            "version >= 1",
            name=op.f("ck_venue_configuration_venue_configuration_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "venue_id"],
            ["venue.tenant_id", "venue.id"],
            name="fk_venue_configuration_venue",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_venue_configuration_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue_configuration")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_venue_configuration_tenant_id_id"),
        sa.UniqueConstraint(
            "venue_id", "name", "version", name="uq_venue_configuration_version"
        ),
    )
    op.create_index(
        op.f("ix_venue_configuration_tenant_id"),
        "venue_configuration",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_venue_configuration_venue",
        "venue_configuration",
        ["tenant_id", "venue_id", "status"],
        unique=False,
    )
    op.create_table(
        "access_zone",
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_access_zone_configuration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_access_zone_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_zone")),
        sa.UniqueConstraint("configuration_id", "code", name="uq_access_zone_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_access_zone_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_access_zone_tenant_id"), "access_zone", ["tenant_id"], unique=False
    )
    op.create_table(
        "price_zone",
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("colour", sa.String(length=9), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_price_zone_configuration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_price_zone_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_zone")),
        sa.UniqueConstraint("configuration_id", "code", name="uq_price_zone_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_price_zone_tenant_id_id"),
    )
    op.create_index(op.f("ix_price_zone_tenant_id"), "price_zone", ["tenant_id"], unique=False)
    op.create_table(
        "season_ticket_product",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("eligibility", sa.String(length=16), nullable=False),
        sa.Column("sales_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renewal_deadline", sa.Date(), nullable=True),
        sa.Column("is_transferable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "eligibility IN ('PUBLIC', 'MEMBERS', 'RENEWAL_ONLY')",
            name=op.f("ck_season_ticket_product_season_product_eligibility_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ON_SALE', 'CLOSED')",
            name=op.f("ck_season_ticket_product_season_product_status_valid"),
        ),
        sa.CheckConstraint(
            "price_minor >= 0",
            name=op.f("ck_season_ticket_product_season_product_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_season_product_configuration",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_season_ticket_product_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season_ticket_product")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_season_product_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_season_ticket_product_tenant_id"),
        "season_ticket_product",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "stand",
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_stand_configuration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_stand_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stand")),
        sa.UniqueConstraint("configuration_id", "code", name="uq_stand_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_stand_tenant_id_id"),
    )
    op.create_index(op.f("ix_stand_tenant_id"), "stand", ["tenant_id"], unique=False)
    op.create_table(
        "ticketed_event",
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("opponent_name", sa.String(length=160), nullable=True),
        sa.Column("competition_label", sa.String(length=120), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("doors_open_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=1), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("presale_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_per_customer", sa.SmallInteger(), nullable=False),
        sa.Column("avoid_orphan_seats", sa.Boolean(), nullable=False),
        sa.Column("fee_per_ticket_minor", sa.Integer(), nullable=False),
        sa.Column("fee_per_order_minor", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "category IN ('A', 'B', 'C')",
            name=op.f("ck_ticketed_event_ticketed_event_category_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED')",
            name=op.f("ck_ticketed_event_ticketed_event_status_valid"),
        ),
        sa.CheckConstraint(
            "max_per_customer > 0",
            name=op.f("ck_ticketed_event_ticketed_event_max_per_customer_positive"),
        ),
        sa.CheckConstraint(
            "sales_end_at IS NULL OR sales_start_at IS NULL OR sales_end_at > sales_start_at",
            name=op.f("ck_ticketed_event_ticketed_event_sales_window_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_ticketed_event_configuration",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "venue_id"],
            ["venue.tenant_id", "venue.id"],
            name="fk_ticketed_event_venue",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ticketed_event_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticketed_event")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_ticketed_event_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_ticketed_event_slug"),
    )
    op.create_index(
        "ix_ticketed_event_kickoff",
        "ticketed_event",
        ["tenant_id", "club_id", "kickoff_at"],
        unique=False,
    )
    op.create_index(
        "ix_ticketed_event_status",
        "ticketed_event",
        ["tenant_id", "club_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticketed_event_tenant_id"), "ticketed_event", ["tenant_id"], unique=False
    )
    op.create_table(
        "access_rule",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("gate_code", sa.String(length=24), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allowed_ticket_types", sa.String(length=240), nullable=True),
        sa.Column("supporter_side", sa.String(length=8), nullable=False),
        sa.Column("allow_reentry", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_access_rule_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_access_rule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_rule")),
        sa.UniqueConstraint("event_id", "gate_code", name="uq_access_rule_gate"),
    )
    op.create_index(
        op.f("ix_access_rule_tenant_id"), "access_rule", ["tenant_id"], unique=False
    )
    op.create_table(
        "allocation",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("owner_name", sa.String(length=160), nullable=True),
        sa.Column("access_code", sa.String(length=32), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('HARD_HOLD', 'SOFT_ALLOCATION')",
            name=op.f("ck_allocation_allocation_kind_valid"),
        ),
        sa.CheckConstraint(
            "reason IN ('SAFETY', 'DEFECTIVE', 'CAMERA_PLATFORM', 'REDUCED_CAPACITY', 'CLOSED_SECTOR', 'SPONSOR', 'PROTOCOL', 'PRESS', 'VIP', 'AWAY_SUPPORTERS', 'ACCESSIBILITY', 'PLAYER_FAMILY', 'OTHER')",
            name=op.f("ck_allocation_allocation_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_allocation_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_allocation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_allocation_tenant_id_id"),
    )
    op.create_index(
        "ix_allocation_event", "allocation", ["tenant_id", "event_id", "kind"], unique=False
    )
    op.create_index(op.f("ix_allocation_tenant_id"), "allocation", ["tenant_id"], unique=False)
    op.create_table(
        "event_configuration_snapshot",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("source_configuration_id", sa.UUID(), nullable=False),
        sa.Column("source_version", sa.SmallInteger(), nullable=False),
        sa.Column("source_name", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_event_snapshot_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_event_configuration_snapshot_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_configuration_snapshot")),
        sa.UniqueConstraint("event_id", name="uq_event_snapshot_event"),
    )
    op.create_index(
        op.f("ix_event_configuration_snapshot_tenant_id"),
        "event_configuration_snapshot",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "event_seat_inventory",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("seat_id", sa.UUID(), nullable=True),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("stand_name", sa.String(length=120), nullable=False),
        sa.Column("section_name", sa.String(length=120), nullable=False),
        sa.Column("section_code", sa.String(length=24), nullable=False),
        sa.Column("section_kind", sa.String(length=24), nullable=False),
        sa.Column("row_label", sa.String(length=12), nullable=True),
        sa.Column("seat_label", sa.String(length=12), nullable=True),
        sa.Column("seat_kind", sa.String(length=24), nullable=False),
        sa.Column("seat_index", sa.SmallInteger(), nullable=False),
        sa.Column("price_zone_code", sa.String(length=24), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("ticket_type_code", sa.String(length=24), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cart_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(state = 'CART_HELD') = (hold_expires_at IS NOT NULL)",
            name=op.f("ck_event_seat_inventory_event_inventory_hold_has_expiry"),
        ),
        sa.CheckConstraint(
            "state IN ('AVAILABLE', 'CART_HELD', 'RESERVED', 'SOLD', 'HARD_BLOCKED', 'SOFT_ALLOCATED', 'COMPLIMENTARY', 'REFUNDED_RELEASED')",
            name=op.f("ck_event_seat_inventory_event_inventory_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_event_inventory_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_event_seat_inventory_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_seat_inventory")),
        sa.UniqueConstraint("event_id", "seat_id", name="uq_event_inventory_seat"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_event_inventory_tenant_id_id"),
    )
    op.create_index(
        "ix_event_inventory_available",
        "event_seat_inventory",
        ["tenant_id", "event_id", "section_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_event_inventory_cart",
        "event_seat_inventory",
        ["tenant_id", "cart_id"],
        unique=False,
    )
    op.create_index(
        "ix_event_inventory_hold_expiry",
        "event_seat_inventory",
        ["state", "hold_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_inventory_order",
        "event_seat_inventory",
        ["tenant_id", "order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_seat_inventory_tenant_id"),
        "event_seat_inventory",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "gate",
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("access_zone_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("supporter_side", sa.String(length=8), nullable=False),
        sa.Column("is_accessible", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('PUBLIC', 'VIP', 'MEDIA', 'STAFF', 'ACCESSIBLE', 'AWAY')",
            name=op.f("ck_gate_gate_kind_valid"),
        ),
        sa.CheckConstraint(
            "supporter_side IN ('ANY', 'HOME', 'AWAY')",
            name=op.f("ck_gate_gate_supporter_side_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "access_zone_id"],
            ["access_zone.tenant_id", "access_zone.id"],
            name="fk_gate_access_zone",
            ondelete="SET NULL (access_zone_id)",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "configuration_id"],
            ["venue_configuration.tenant_id", "venue_configuration.id"],
            name="fk_gate_configuration",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_gate_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate")),
        sa.UniqueConstraint("configuration_id", "code", name="uq_gate_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_gate_tenant_id_id"),
    )
    op.create_index(op.f("ix_gate_tenant_id"), "gate", ["tenant_id"], unique=False)
    op.create_table(
        "gate_assignment",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("gate_code", sa.String(length=24), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "device_id"],
            ["scanner_device.tenant_id", "scanner_device.id"],
            name="fk_gate_assignment_device",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_gate_assignment_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_gate_assignment_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_assignment")),
        sa.UniqueConstraint("device_id", "event_id", name="uq_gate_assignment_device_event"),
    )
    op.create_index(
        "ix_gate_assignment_event", "gate_assignment", ["tenant_id", "event_id"], unique=False
    )
    op.create_index(
        op.f("ix_gate_assignment_tenant_id"), "gate_assignment", ["tenant_id"], unique=False
    )
    op.create_table(
        "scan_log",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("presented_reference", sa.String(length=64), nullable=True),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("gate_code", sa.String(length=24), nullable=True),
        sa.Column("operator_name", sa.String(length=160), nullable=True),
        sa.Column("scan_type", sa.String(length=8), nullable=False),
        sa.Column("result", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("server_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("was_offline", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "result IN ('VALID', 'ALREADY_USED', 'WRONG_GATE', 'WRONG_EVENT', 'NOT_YET_VALID', 'EXPIRED', 'CANCELLED', 'REFUNDED', 'DEVICE_REVOKED', 'UNKNOWN_CREDENTIAL')",
            name=op.f("ck_scan_log_scan_log_result_valid"),
        ),
        sa.CheckConstraint(
            "scan_type IN ('ENTRY', 'EXIT')", name=op.f("ck_scan_log_scan_log_scan_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_scan_log_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_scan_log_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_log")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_scan_log_idempotency"),
    )
    op.create_index(
        "ix_scan_log_event_time",
        "scan_log",
        ["tenant_id", "event_id", "server_at"],
        unique=False,
    )
    op.create_index(
        "ix_scan_log_gate",
        "scan_log",
        ["tenant_id", "event_id", "gate_code", "result"],
        unique=False,
    )
    op.create_index(op.f("ix_scan_log_tenant_id"), "scan_log", ["tenant_id"], unique=False)
    op.create_index(
        "uq_scan_log_valid_entry",
        "scan_log",
        ["credential_id"],
        unique=True,
        postgresql_where=sa.text("result = 'VALID' AND scan_type = 'ENTRY'"),
    )
    op.create_table(
        "season_pass",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("seat_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("holder_name", sa.String(length=160), nullable=False),
        sa.Column("holder_email", sa.String(length=320), nullable=True),
        sa.Column("supporter_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("price_paid_minor", sa.Integer(), nullable=False),
        sa.Column("stand_name", sa.String(length=120), nullable=True),
        sa.Column("section_name", sa.String(length=120), nullable=True),
        sa.Column("row_label", sa.String(length=12), nullable=True),
        sa.Column("seat_label", sa.String(length=12), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACTIVE', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_season_pass_season_pass_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["season_ticket_product.tenant_id", "season_ticket_product.id"],
            name="fk_season_pass_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_season_pass_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season_pass")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_season_pass_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "reference", name="uq_season_pass_reference"),
    )
    op.create_index(
        op.f("ix_season_pass_tenant_id"), "season_pass", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_season_pass_seat_live",
        "season_pass",
        ["product_id", "seat_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"),
    )
    op.create_table(
        "season_ticket_event",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_season_ticket_event_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["season_ticket_product.tenant_id", "season_ticket_product.id"],
            name="fk_season_ticket_event_product",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_season_ticket_event_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season_ticket_event")),
        sa.UniqueConstraint("product_id", "event_id", name="uq_season_ticket_event"),
    )
    op.create_index(
        op.f("ix_season_ticket_event_tenant_id"),
        "season_ticket_event",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "section",
        sa.Column("stand_id", sa.UUID(), nullable=False),
        sa.Column("price_zone_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("declared_capacity", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('RESERVED', 'GENERAL_ADMISSION')",
            name=op.f("ck_section_section_kind_valid"),
        ),
        sa.CheckConstraint(
            "declared_capacity >= 0", name=op.f("ck_section_section_capacity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "price_zone_id"],
            ["price_zone.tenant_id", "price_zone.id"],
            name="fk_section_price_zone",
            ondelete="SET NULL (price_zone_id)",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "stand_id"],
            ["stand.tenant_id", "stand.id"],
            name="fk_section_stand",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_section_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section")),
        sa.UniqueConstraint("stand_id", "code", name="uq_section_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_section_tenant_id_id"),
    )
    op.create_index(op.f("ix_section_tenant_id"), "section", ["tenant_id"], unique=False)
    op.create_table(
        "event_entitlement",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("season_pass_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("order_line_id", sa.UUID(), nullable=True),
        sa.Column("ticket_type_code", sa.String(length=24), nullable=False),
        sa.Column("holder_name", sa.String(length=160), nullable=True),
        sa.Column("supporter_id", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(source = 'SEASON_PASS') = (season_pass_id IS NOT NULL)",
            name=op.f("ck_event_entitlement_entitlement_season_pass_matches_source"),
        ),
        sa.CheckConstraint(
            "source IN ('SINGLE', 'SEASON_PASS', 'COMPLIMENTARY')",
            name=op.f("ck_event_entitlement_entitlement_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RELEASED', 'TRANSFERRED', 'CANCELLED', 'REFUNDED')",
            name=op.f("ck_event_entitlement_entitlement_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["ticketed_event.tenant_id", "ticketed_event.id"],
            name="fk_entitlement_event",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "inventory_id"],
            ["event_seat_inventory.tenant_id", "event_seat_inventory.id"],
            name="fk_entitlement_inventory",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_event_entitlement_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_entitlement")),
        sa.UniqueConstraint("inventory_id", name="uq_entitlement_seat"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_entitlement_tenant_id_id"),
    )
    op.create_index(
        "ix_entitlement_event_status",
        "event_entitlement",
        ["tenant_id", "event_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_entitlement_pass",
        "event_entitlement",
        ["tenant_id", "season_pass_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_entitlement_tenant_id"), "event_entitlement", ["tenant_id"], unique=False
    )
    op.create_table(
        "gate_section",
        sa.Column("gate_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "gate_id"],
            ["gate.tenant_id", "gate.id"],
            name="fk_gate_section_gate",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "section_id"],
            ["section.tenant_id", "section.id"],
            name="fk_gate_section_section",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_gate_section_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_section")),
        sa.UniqueConstraint("gate_id", "section_id", name="uq_gate_section"),
    )
    op.create_index(
        op.f("ix_gate_section_tenant_id"), "gate_section", ["tenant_id"], unique=False
    )
    op.create_table(
        "seat_row",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=12), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "section_id"],
            ["section.tenant_id", "section.id"],
            name="fk_seat_row_section",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_seat_row_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seat_row")),
        sa.UniqueConstraint("section_id", "label", name="uq_seat_row_label"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_seat_row_tenant_id_id"),
    )
    op.create_index(op.f("ix_seat_row_tenant_id"), "seat_row", ["tenant_id"], unique=False)
    op.create_table(
        "seat",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("row_id", sa.UUID(), nullable=False),
        sa.Column("price_zone_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=12), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("seat_index", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('STANDARD', 'WHEELCHAIR', 'COMPANION', 'OBSTRUCTED_VIEW')",
            name=op.f("ck_seat_seat_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "price_zone_id"],
            ["price_zone.tenant_id", "price_zone.id"],
            name="fk_seat_price_zone",
            ondelete="SET NULL (price_zone_id)",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "row_id"],
            ["seat_row.tenant_id", "seat_row.id"],
            name="fk_seat_row",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "section_id"],
            ["section.tenant_id", "section.id"],
            name="fk_seat_section",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_seat_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seat")),
        sa.UniqueConstraint("row_id", "label", name="uq_seat_label"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_seat_tenant_id_id"),
    )
    op.create_index("ix_seat_section", "seat", ["tenant_id", "section_id"], unique=False)
    op.create_index(op.f("ix_seat_tenant_id"), "seat", ["tenant_id"], unique=False)
    op.create_table(
        "ticket",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("entitlement_id", sa.UUID(), nullable=False),
        sa.Column("ticket_number", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("ticket_type_code", sa.String(length=24), nullable=False),
        sa.Column("ticket_type_name", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("vat_minor", sa.Integer(), nullable=False),
        sa.Column("fee_minor", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("season_pass_id", sa.UUID(), nullable=True),
        sa.Column("holder_name", sa.String(length=160), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ISSUED', 'VOID', 'REFUNDED')",
            name=op.f("ck_ticket_ticket_status_valid"),
        ),
        sa.CheckConstraint(
            "price_minor >= 0", name=op.f("ck_ticket_ticket_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entitlement_id"],
            ["event_entitlement.tenant_id", "event_entitlement.id"],
            name="fk_ticket_entitlement",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ticket_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket")),
        sa.UniqueConstraint("entitlement_id", name="uq_ticket_entitlement"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_ticket_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "ticket_number", name="uq_ticket_number"),
    )
    op.create_index(
        "ix_ticket_event", "ticket", ["tenant_id", "event_id", "status"], unique=False
    )
    op.create_index("ix_ticket_order", "ticket", ["tenant_id", "order_id"], unique=False)
    op.create_index(op.f("ix_ticket_tenant_id"), "ticket", ["tenant_id"], unique=False)
    op.create_table(
        "access_credential",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.String(length=120), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("gate_codes", sa.String(length=240), nullable=True),
        sa.Column("section_code", sa.String(length=24), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'REVOKED', 'SUPERSEDED')",
            name=op.f("ck_access_credential_credential_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ticket_id"],
            ["ticket.tenant_id", "ticket.id"],
            name="fk_credential_ticket",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_access_credential_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_credential")),
        sa.UniqueConstraint("reference", name="uq_credential_reference"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_credential_tenant_id_id"),
    )
    op.create_index(
        op.f("ix_access_credential_tenant_id"), "access_credential", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_credential_ticket", "access_credential", ["tenant_id", "ticket_id"], unique=False
    )
    op.create_index(
        "uq_credential_active_per_ticket",
        "access_credential",
        ["ticket_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    for statement in enable_all(RLS_TABLES):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for statement in disable_all(RLS_TABLES):
        op.execute(statement)
    op.drop_index(
        "uq_credential_active_per_ticket",
        table_name="access_credential",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index("ix_credential_ticket", table_name="access_credential")
    op.drop_index(op.f("ix_access_credential_tenant_id"), table_name="access_credential")
    op.drop_table("access_credential")
    op.drop_index(op.f("ix_ticket_tenant_id"), table_name="ticket")
    op.drop_index("ix_ticket_order", table_name="ticket")
    op.drop_index("ix_ticket_event", table_name="ticket")
    op.drop_table("ticket")
    op.drop_index(op.f("ix_seat_tenant_id"), table_name="seat")
    op.drop_index("ix_seat_section", table_name="seat")
    op.drop_table("seat")
    op.drop_index(op.f("ix_seat_row_tenant_id"), table_name="seat_row")
    op.drop_table("seat_row")
    op.drop_index(op.f("ix_gate_section_tenant_id"), table_name="gate_section")
    op.drop_table("gate_section")
    op.drop_index(op.f("ix_event_entitlement_tenant_id"), table_name="event_entitlement")
    op.drop_index("ix_entitlement_pass", table_name="event_entitlement")
    op.drop_index("ix_entitlement_event_status", table_name="event_entitlement")
    op.drop_table("event_entitlement")
    op.drop_index(op.f("ix_section_tenant_id"), table_name="section")
    op.drop_table("section")
    op.drop_index(op.f("ix_season_ticket_event_tenant_id"), table_name="season_ticket_event")
    op.drop_table("season_ticket_event")
    op.drop_index(
        "uq_season_pass_seat_live",
        table_name="season_pass",
        postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"),
    )
    op.drop_index(op.f("ix_season_pass_tenant_id"), table_name="season_pass")
    op.drop_table("season_pass")
    op.drop_index(
        "uq_scan_log_valid_entry",
        table_name="scan_log",
        postgresql_where=sa.text("result = 'VALID' AND scan_type = 'ENTRY'"),
    )
    op.drop_index(op.f("ix_scan_log_tenant_id"), table_name="scan_log")
    op.drop_index("ix_scan_log_gate", table_name="scan_log")
    op.drop_index("ix_scan_log_event_time", table_name="scan_log")
    op.drop_table("scan_log")
    op.drop_index(op.f("ix_gate_assignment_tenant_id"), table_name="gate_assignment")
    op.drop_index("ix_gate_assignment_event", table_name="gate_assignment")
    op.drop_table("gate_assignment")
    op.drop_index(op.f("ix_gate_tenant_id"), table_name="gate")
    op.drop_table("gate")
    op.drop_index(op.f("ix_event_seat_inventory_tenant_id"), table_name="event_seat_inventory")
    op.drop_index("ix_event_inventory_order", table_name="event_seat_inventory")
    op.drop_index("ix_event_inventory_hold_expiry", table_name="event_seat_inventory")
    op.drop_index("ix_event_inventory_cart", table_name="event_seat_inventory")
    op.drop_index("ix_event_inventory_available", table_name="event_seat_inventory")
    op.drop_table("event_seat_inventory")
    op.drop_index(
        op.f("ix_event_configuration_snapshot_tenant_id"),
        table_name="event_configuration_snapshot",
    )
    op.drop_table("event_configuration_snapshot")
    op.drop_index(op.f("ix_allocation_tenant_id"), table_name="allocation")
    op.drop_index("ix_allocation_event", table_name="allocation")
    op.drop_table("allocation")
    op.drop_index(op.f("ix_access_rule_tenant_id"), table_name="access_rule")
    op.drop_table("access_rule")
    op.drop_index(op.f("ix_ticketed_event_tenant_id"), table_name="ticketed_event")
    op.drop_index("ix_ticketed_event_status", table_name="ticketed_event")
    op.drop_index("ix_ticketed_event_kickoff", table_name="ticketed_event")
    op.drop_table("ticketed_event")
    op.drop_index(op.f("ix_stand_tenant_id"), table_name="stand")
    op.drop_table("stand")
    op.drop_index(
        op.f("ix_season_ticket_product_tenant_id"), table_name="season_ticket_product"
    )
    op.drop_table("season_ticket_product")
    op.drop_index(op.f("ix_price_zone_tenant_id"), table_name="price_zone")
    op.drop_table("price_zone")
    op.drop_index(op.f("ix_access_zone_tenant_id"), table_name="access_zone")
    op.drop_table("access_zone")
    op.drop_index("ix_venue_configuration_venue", table_name="venue_configuration")
    op.drop_index(op.f("ix_venue_configuration_tenant_id"), table_name="venue_configuration")
    op.drop_table("venue_configuration")
    op.drop_index(op.f("ix_price_rule_tenant_id"), table_name="price_rule")
    op.drop_table("price_rule")
    op.drop_index(op.f("ix_device_enrollment_tenant_id"), table_name="device_enrollment")
    op.drop_index("ix_device_enrollment_device", table_name="device_enrollment")
    op.drop_table("device_enrollment")
    op.drop_index(op.f("ix_venue_tenant_id"), table_name="venue")
    op.drop_index("ix_venue_club", table_name="venue")
    op.drop_table("venue")
    op.drop_index(op.f("ix_ticket_type_tenant_id"), table_name="ticket_type")
    op.drop_table("ticket_type")
    op.drop_index(op.f("ix_scanner_device_tenant_id"), table_name="scanner_device")
    op.drop_index("ix_scanner_device_status", table_name="scanner_device")
    op.drop_table("scanner_device")
    op.drop_index(op.f("ix_promo_code_tenant_id"), table_name="promo_code")
    op.drop_table("promo_code")
    op.drop_index(op.f("ix_price_list_tenant_id"), table_name="price_list")
    op.drop_index("ix_price_list_lookup", table_name="price_list")
    op.drop_table("price_list")
    # ### end Alembic commands ###
